name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: './frontend' # Ruta de la carpeta frontend en tu repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: frontend # Cambio de directorio a frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend # Cambio de directorio a frontend
        run: npm test
